### ISSUE TITLE
Make sure any error while sending an email is handled by throwing an exception

### ISSUE THREAD

**Issue by acelaya** [acmailer/acmailer#266]
For historical reasons, the `send` method returns a mail result, which has a `isValid` method telling you if the email was properly sent.

However, it can also throw an exception, which introduces two paths to handle errors while calling send.

```php
try {
    $result = $mailService->send(...);
    if (! $result->isValid()) {
        // Email was not properly sent
    }
} catch (MailException $e) {
    // Email was also not properly sent
}
```

In order to simplify this, let's change the internal logic to make sure any error is always thrown as an exception (in fact, it's probable that this is already the case).

Let's also mark the `isValid` method as deprecated, and remove any reference from the documentation.

**Comment by dlondero** [comment]
@acelaya AFAIU there is only one case where `MailResult` is returned `false` and it is in here: https://github.com/acmailer/acmailer/blob/main/src/Service/MailService.php#L94-L96. Would it be ok to throw a new `MailCancelledException` which extends `MailException` so the exception message could be customised?

Use case would become:
```php
try {
    $result = $mailService->send(...);
} catch (MailException $e) {
    // Email was also not properly sent
}
```

**Comment by acelaya** [comment]
> AFAIU there is only one case where MailResult is returned false and it is in here: https://github.com/acmailer/acmailer/blob/main/src/Service/MailService.php#L94-L96.

Good point. I missed that.

> Would it be ok to throw a new MailCancelledException which extends MailException

Yes, I like the approach. Considering the `send` method can already throw exceptions, this would be backwards compatible (technically speaking).

I have to check the docs, though, to make sure nothing will break for any user.

**Comment by dlondero** [comment]
On the other end maybe `MailCancelledException` could just be thrown inside the try/catch in https://github.com/acmailer/acmailer/blob/main/src/Service/MailService.php#L98-L118 and not extend `MailException`. In the end it would be anyway available as previous exception inside `MailException`. This would make more sense I guess.

**Comment by acelaya** [comment]
I have actually realized this would indeed be a breaking change, and therefore it needs a major version to do it.

What I'm thinking is to introduce a config option for mail services, a flag like `throw_on_cancel`, which defaults to false, but can be set to true to make it always throw as you proposed.

Then, once v9 gets eventually released, the flag is removed and it's changed to always throw, add well as removing the `isValid` method.

> On the other end maybe MailCancelledException could just be thrown inside the try/catch in https://github.com/acmailer/acmailer/blob/main/src/Service/MailService.php#L98-L118 and not extend MailException. In the end it would be anyway available as previous exception inside MailException. This would make more sense I guess.

I actually think the first approach made more sense, because it gives you the flexibility to handle the cancel transparently as any other error, or instead, having something like this.

```php
try {
    $result = $mailService->send(...);
} catch (MailCancelledException $e) {
    // Email was cancelled
} catch (MailException $e) {
    // Email was not sent because of an error
}
```

If you wrap it, somewhere you would need an ugly `if ($e->getPrevious() instanceof MailCancelledException)` or something in those lines.

**Comment by acelaya** [comment]
> Also MailResult::isCancelled would need to be changed in order to verify if the throwable is an instance of MailCancelledException.

True, that needs to be handled.

**Comment by dlondero** [comment]
Yep, this would definitely introduce a BC break as `MailResult` would not be returned anymore for the cancellation case.
Agree on throwing directly `MailCancelledException` w/o wrapping it when the new `throw_on_cancel` flag is set to `true`.
I'll propose a PR then!

**Comment by dlondero** [comment]
@acelaya quick question: passing the value of the new flag `throw_on_cancel` could be easily done via the `$options` array that can be passed to `MailService::send()` but that would make it an `email` configuration (looking at the docs) which I think is not extremely correct even if it's temporary until next major release. 

```php
$this->mailService->send(new Email(), ['throw_on_cancel' => true]);
```

I think it should be a general `mail_service` configuration parameter. Would it be ok to inject it into `MailService` as a boolean parameter in the constructor when calling it in the factory? Wdyt?

```php
return [
    'acmailer_options' => [
        'mail_services' => [
            'throw_on_cancel' => false,
            'default' => [ ...
```

**Comment by acelaya** [comment]
Yep, it should be part of the service config, not part of the email options, as it's something not very likely to change at runtime, so your second proposal is what I had in mind too.

As per how to inject it in the service, I guess a boolean in the constructor should be enough.
